name: GLaDOS-checkin

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 */6 * * *

jobs:
  GLaDOS-checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set execute permissions for checkin.sh
        run: chmod +x checkin.sh
      - name: checkin
        env:
          COOKIE: ${{ secrets.COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          ./checkin.sh
